spring.application.name=appgraph

# Spring Boot Actuator Configs 
management.endpoints.web.exposure.include=*
management.info.os.enabled=true
management.info.java.enabled=true
management.info.build.enabled=true
management.info.git.enabled=true
management.info.git.mode=full
management.info.env.enabled=true

# Info Actuator - Custom Configs
info.application.name=appgraph
info.application.description=A SpringBoot+Neo4j application for modeling a graph of IT Enterprise applications
info.application.created=April 2026
info.application.author.name=Philip Posgate
info.application.author.email=philip.posgate@gmail.com

# Pretty-print JSON responses
 spring.jackson.serialization.indent_output=true

# logging configs
logging.level.org.springframework=ERROR
logging.level.ca.appgraph=DEBUG
#logging.file.name=appgraph.log
logging.pattern.file=%d %p %c{1.} [%t] %m%n
logging.pattern.console=%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n

#neo4j configs
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=password

logging.level.org.springframework.data.neo4j=DEBUG
